env: "local" # local, dev, prod
storage_path: "host=localhost user=admin password=123456 dbname=mydb port=5432 sslmode=disable"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypass"

redis:
  address: localhost:6379
  password: ""
  db: 0